sonar.projectKey=api-test-framework
sonar.projectName=API Test Automation Framework
sonar.sources=src/main
sonar.tests=src/test
sonar.java.binaries=build/classes
sonar.sourceEncoding=UTF-8
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
